### ISSUE TITLE
[Bug] TypeError: Readable.from is not a function

### ISSUE THREAD

**Issue by overtube** [remoteintech/remote-jobs#1758]
`./build-site.js`

```
Parsing content
Requesting URL "https://blog.remoteintech.company/"
Requesting URL "https://s2.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/b..."
Requesting URL "https://s0.wp.com/_static/??-eJyVjV0OwiAQBi8kEKrR+mA8C4UN2br8hAVNby..."
Requesting URL "https://s1.wp.com/_static/??/wp-content/mu-plugins/core-compat/wp-m..."
Requesting URL "https://s0.wp.com/_static/??-eJyVkNsKAjEMRH/IGC/g5UH8llrjWrdtyiZF/H..."
Requesting URL "https://s1.wp.com/wp-content/mu-plugins/global-print/global-print.c..."
Requesting URL "https://s2.wp.com/wp-content/themes/h4/global.css?m=1420737423i&css..."
Requesting URL "https://s0.wp.com/?custom-css=1&csblog=9eXnX&cscache=6&csrev=6"
Requesting URL "https://s2.wp.com/wp-content/mu-plugins/widgets/eu-cookie-law/templ..."
Copying favicon files
Generating search index
Writing main page
Writing company pages.................................................................................
Writing custom 404 page

Writing empty robots.txt

Site files are ready in "site/build/"
Aborted
```

`/remote-jobs/bin$ ./serve-site.js`

```
Parsing content
Requesting URL "https://blog.remoteintech.company/"
Requesting URL "https://s2.wp.com/wp-content/plugins/gutenberg-core/v16.9.0/build/b..."
Requesting URL "https://s0.wp.com/_static/??-eJyVjV0OwiAQBi8kEKrR+mA8C4UN2br8hAVNby..."
Requesting URL "https://s1.wp.com/_static/??/wp-content/mu-plugins/core-compat/wp-m..."
Requesting URL "https://s0.wp.com/_static/??-eJyVkNsKAjEMRH/IGC/g5UH8llrjWrdtyiZF/H..."
Requesting URL "https://s1.wp.com/wp-content/mu-plugins/global-print/global-print.c..."
Requesting URL "https://s2.wp.com/wp-content/themes/h4/global.css?m=1420737423i&css..."
Requesting URL "https://s0.wp.com/?custom-css=1&csblog=9eXnX&cscache=6&csrev=6"
Requesting URL "https://s2.wp.com/wp-content/mu-plugins/widgets/eu-cookie-law/templ..."
Copying favicon files
Generating search index
Writing main page
Writing company pages.................................................................................
Writing custom 404 page

Writing empty robots.txt

Site files are ready in "site/build/"
Starting up http-server, serving 
/remote-jobs/site/build

http-server version: 14.0.0

http-server settings: 
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  **http://127.0.0.1:8080**
  **http://192.168.0.102:8080**
Hit CTRL-C to stop the server

[Mon Nov 13 2023 02:04:51 GMT+0200 (GMT+02:00)]  "GET /" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
/home/ui/Templates/@/junk/js/remote-jobs/node_modules/http-server/lib/core/index.js:246
          stream = Readable.from(bytes)
                            ^

TypeError: Readable.from is not a function
    at serve (/home/ui/Templates/@/junk/js/remote-jobs/node_modules/http-server/lib/core/index.js:246:29)
    at fs.stat (/home/ui/Templates/@/junk/js/remote-jobs/node_modules/http-server/lib/core/index.js:419:13)
    at FSReqWrap.oncomplete (fs.js:159:5)
Aborted
```

**Comment by dougaitken** [comment]
Thanks @overtube, I've not been involved in that side but I'm aiming to move the site build system ASAP so hopefully there will be an update soon.

**Comment by overtube** [comment]
Glad help, thank for that nice site

**Comment by chethanac15** [comment]
//assign
